  DEBUG: True
  TESTING: True
  ALLOWED_EXTENSIONS: ['jpg', 'jpeg', 'png']
  LOGFILE: app.log
  UPLOAD_FOLDER: uploads
  RESULT_FOLDER: results
  CELERY_BROKER_URL: redis://redis:6379/0
  CELERY_RESULT_BACKEND: redis://redis:6379/0